# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AssaioAgent < Formula
  desc "Is your AI coding spend delivering? Offline, per-project analytics for Claude Code, Codex, Gemini CLI, and Cline."
  homepage "https://github.com/assaio/assaio"
  version "0.10.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/assaio/assaio/releases/download/v0.10.0/assaio_0.10.0_darwin_amd64.tar.gz"
      sha256 "49d701842029021099d08b2b5c1f292885e35031df46b16e8a1b895fbdd35efd"

      define_method(:install) do
        bin.install "assaio-agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/assaio/assaio/releases/download/v0.10.0/assaio_0.10.0_darwin_arm64.tar.gz"
      sha256 "d5934dcaf20995e36cd893d28c6a42593a7573eb598949ec96971c2f289ca89a"

      define_method(:install) do
        bin.install "assaio-agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/assaio/assaio/releases/download/v0.10.0/assaio_0.10.0_linux_amd64.tar.gz"
      sha256 "b60e47676da8448525e828001476f6314e26832a43e5601ad0556f5106609beb"
      define_method(:install) do
        bin.install "assaio-agent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/assaio/assaio/releases/download/v0.10.0/assaio_0.10.0_linux_arm64.tar.gz"
      sha256 "8473c28e20b93e22c51902f2c1fc278b10e801a4a6984c422871b726cf8672ed"
      define_method(:install) do
        bin.install "assaio-agent"
      end
    end
  end

  test do
    system "#{bin}/assaio-agent", "--version"
  end
end
