# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AssaioAgent < Formula
  desc "Offline usage, cost, and code-activity analytics for AI coding tools."
  homepage "https://github.com/assaio/assaio"
  version "0.28.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/assaio/assaio/releases/download/v0.28.0/assaio_0.28.0_darwin_amd64.tar.gz"
      sha256 "3c985897625565e42d928fb98c49c9ab23df8b6dfd2924730fe43c6f3941656e"

      define_method(:install) do
        bin.install "assaio-agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/assaio/assaio/releases/download/v0.28.0/assaio_0.28.0_darwin_arm64.tar.gz"
      sha256 "ca58f6378bfaba86f385c188d90d55f65b06e7313b3f5568707261fd04a04745"

      define_method(:install) do
        bin.install "assaio-agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/assaio/assaio/releases/download/v0.28.0/assaio_0.28.0_linux_amd64.tar.gz"
      sha256 "58c044b53df82ab4f5435ebafb58f4181d1e36718dcf2dfd7263016d1edfc7ee"
      define_method(:install) do
        bin.install "assaio-agent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/assaio/assaio/releases/download/v0.28.0/assaio_0.28.0_linux_arm64.tar.gz"
      sha256 "32df1b58bb01bf62a55f60db6b4c039ff284a9a89132a5fc34c1cbeda7ace58d"
      define_method(:install) do
        bin.install "assaio-agent"
      end
    end
  end

  test do
    system "#{bin}/assaio-agent", "--version"
  end
end
